pipeline {
    agent { docker { image 'maven:3.3.3' } }
        tools {
        maven 'Maven 3.3.9'
        jdk 'jdk11'
    }
    stages {
       stage('Initialize'){
        steps {
               echo 'initialize...'
        }
        
        }

         stage ('Build') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true install' 
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml' 
                }
            }
        }
    }
} 
