pipeline {
    agent { docker { image 'maven:3.3.3' } }
    stages {
       stage('Initialize'){
        steps {
            script {
                def dockerHome = tool 'myDocker'
                env.PATH = "${dockerHome}/bin:${env.PATH}" }
        }
           echo 'initialize..'
        }
        stage('build') {
            steps {
                sh 'mvn --version'
                 echo 'build..'
            }
        }
    }
} 
