pipeline {
    agent { docker { image 'maven:3.3.3' } }
        tools { 
        jdk 'OpenJDK-11' 
    }
    stages {
       stage('Initialize'){
        steps {
               echo 'initialize...'
        }
        
        }

         stage ('Build') {
            steps {
                sh ''' 
                echo "JAVA_HOME = ${JAVA_HOME}"

                cd VideoService
                mvn -Dmaven.test.failure.ignore=true install
                '''
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml' 
                }
            }
        }
    }
} 
