apiVersion: apps/v1
kind: Deployment
metadata:
  name: videoservicejs
  labels:
    app: videoservicejs
spec:
  selector: 
    matchLabels:
      app: videoservicejs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: videoservicejs
        tier: videoservicejs
    spec:
      # selector: 
      #   matchLabels:
      #     app: VideoServiceJS
      containers:
        - name: videoservicejs
          image: mvisoromero/videoservicejs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              name: videoservicejs

---
apiVersion: v1
kind: Service
metadata:
  name: videoservicejs
  labels:
    app: videoservicejs
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: twitch2
    tier: twitch2
  type: LoadBalancer
